# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fault_buffer_tool_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


